# Copied almost verbatim from https://github.com/marketplace/actions/sphinx-build
name: sphinx
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
